name: MacOS Unit Tests
on:
    pull_request: {}
    push: {}

jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run unit tests on MacOS
      run: go test -v -race ./iscsi/...
