name: Static Checks
on:
    pull_request: {}
    push: {}
jobs:
    go_lint:
        name: Go Lint
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go 1.x
              uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
              with:
                go-version: ^1.19
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - name: Run linter
              uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3
              with:
                  version: v1.64
                  args: -E=gofmt,unused,ineffassign,revive,misspell,asciicheck,bodyclose,contextcheck,dogsled,durationcheck,errname,forbidigo -D=staticcheck --timeout=30m0s
