name: Static Checks
on:
    pull_request: {}
    push: {}
jobs:
    go_lint:
        name: Go Lint
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go 1.x
              uses: actions/setup-go@v4
              with:
                go-version: ^1.19
            - uses: actions/checkout@master
            - name: Run linter
              uses: golangci/golangci-lint-action@v4
              with:
                  version: v1.51
                  args: -E=gofmt,deadcode,unused,varcheck,ineffassign,revive,misspell,exportloopref,asciicheck,bodyclose,contextcheck,depguard,dogsled,durationcheck,errname,forbidigo -D=staticcheck --timeout=30m0s
