name: Windows Tests
on:
    pull_request: {}
    push: {}
jobs:
  build:
    strategy:
      matrix:
        go-versions: [1.19.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19
        id: go
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Test
        run: |
          go build -a -o example/iscsi-lib-example.exe ./example
